#!/usr/bin/env node

import * as fs from "node:fs";
import * as path from "node:path";
import { program } from "commander";
import { openApiToSourceCode } from "./OpenApiToSourceCode";

program.name("api-def");

const packageJson = JSON.parse(fs.readFileSync("package.json", "utf-8"));
program.version(packageJson.version);

program
  .command("generate")
  .argument("<inPath>", "Path to the OpenAPI spec")
  .argument("<outPath>", "Path to the output file")
  .description("Generate an api-def from an OpenAPI spec")
  .action(async (inPath, outPath) => {
    const resolvedInPath = path.resolve(inPath);
    if (!fs.existsSync(resolvedInPath)) {
      console.error(`File not found: ${resolvedInPath}`);
      process.exit(1);
    }

    const output = await openApiToSourceCode({
      openApiPath: resolvedInPath,
    });
    fs.writeFileSync(path.resolve(outPath), `// Generated by 'api-def' version ${packageJson.version}\n${output}`);
    console.log(`Generated api-def at ${outPath}`);
  });

program.parse(process.argv);
