name = "api-def-website"
compatibility_date = "2026-08-21"
workers_dev = false

[assets]
directory = "./build"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[env.main]
workers_dev = false
routes = [
  { pattern = "api-def.com", custom_domain = true },
]
